</main>

<!-- main footer -->
<footer class="d-flex flex-column justify-content-center align-items-center py-1 my-4 border-top">
      <div class="align-items-center">
         <span class="text-muted">TRABAJO PRACTICO ESPECIAL 2 - 2025 </span>
      </div>
       <div class="align-items-center">
         <span class="text-muted"> Integrantes : Machado Facundo y Machado Maximiliano</span>
      </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>