<form action="agregarAlbum" method="POST" class="d-flex flex-wrap align-items-center justify-content-center gap-3 p-3"
    style="background-color: transparent;"> 
    <div class="d-flex flex-column text-center ">
        <label class="form-label mb-1 ">Álbum:</label>
        <input type="text" name="nombre" required
           class="form-control rounded-pill bg-transparent  border-dark"
           placeholder="Nombre">
     </div>

    
    <div class="d-flex flex-column text-center ">
        <label  class="form-label mb-1 ">Año de Lanzamiento:</label>
        <input type="number" name="anio_lanzamiento" required
           class="form-control rounded-pill bg-transparent  border-dark"
           placeholder="Año lanzamiento">
    </div>

    <div class="d-flex flex-column align-items-center text-center">
        <button type="submit" class="btn btn-outline-success rounded-pill px-4 mt-4" >Agregar</button>
    </div>
    
</form>