<div style="text-align: center; margin-top: 50px; ">
    <img src="icono/user.jpg" alt="login" width="200" height="200">
</div>

<form action="do_login" method="POST" class="my-4 d-flex flex-column align-items-center text-center">
    <div class="form-group mb-3" style="width: 500px;">
        <label >Usuario</label>
        <input required name="user" type="text" class="form-control">
    </div>
    <div class="form-group mb-3" style="width: 500px;">
        <label>Contraseña</label>
        <input required name="password" type="password" class="form-control">
    </div>
    <div class="text-danger mb-2">
        <?php if (!empty($error)): ?>
            <?=$error?>
        <?php endif; ?>
    </div>
    <button type="submit" class="btn btn-dark  mt-3" style="width: 150px;"> Login</button>
</form>
