<!DOCTYPE html>
<html lang="es">
<head>
    <base href="<?= BASE_URL ?>"> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Document</title>
</head>
<body>


    
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
   <a class="navbar-brand bebas-neue-regular" href="inicio">Inicio</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="albumes">Albumes</a>
        </li>
       <li class="nav-item ml-auto">
          <?php if ($user): ?>
              <a class="nav-link" aria-current="page" href="logout">Salir</a>
          <?php else: ?>
              <a class="nav-link" aria-current="page" href="login">Ingresar</a>
          <?php endif; ?>
        </li>
      </ul>
    </div>
  </div>
</nav>


</body>
</html>