<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

<?php  
  if ($user): 
    require_once './templates/formularioAgregarCancion.phtml';
  endif
?>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Álbum</th>
      <th scope="col">Canción</th>
      <th scope="col">Duración</th>
      <th scope="col">Letra explícita</th>
    </tr>
  </thead>
  <tbody>

    <?php foreach($albumCanciones as $album_cancion){
      echo "<tr>";
          echo "<td> " . $album_cancion->nombre_album . "</td>";
          echo "<td>" . $album_cancion->nombre_cancion . "</td>";
          echo "<td>" . $album_cancion->duracion . "</td>"; 
          echo "<td>" . ($album_cancion->letra_explicita ? 'Si' : 'No') . "</td>";
          if($user): 
            echo "<td><a href=detalleCancion/" . $album_cancion->id . "'  class='btn btn-outline-primary'>Ver</a></td>";
            echo "<td><a  href= 'botonEditar/" . $album_cancion->id . "' class='btn btn-outline-secondary'>Editar</a></td>";
            echo "<td><a href= 'eliminar/" . $album_cancion->id . "' class='btn btn-outline-danger'>Eliminar</a></td>";
          endif; 
              
     echo "</tr>";
    }

  ?>
  </tbody>
</table>

<?php if($user): ?>
    <form class="d-flex align-items-center" method="POST" action="filtrar">
      <label class="me-2 mb-0">Albumes</label>
        <select required name="album" class="form-control text-center me-2" style="width: 200px;">
          <?php foreach ($albumes as $album) : ?>
            <option value="<?= $album->id ?>"> <?= $album->nombre?> </option>
          <?php endforeach ?>
        </select>
        <button type="submit" class="btn btn-outline-dark">Filtrar</button>
    </form>
<?php endif;?>


